name = "GSEA"
uuid = "d7bef1b9-4643-4ed1-9ceb-ed43dd382ec0"
authors = ["Kwat Medetgul-Ernar <kwat.me@icloud.com>"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Plot = "9db1e993-d40e-4a2c-9c84-e29bd56acb85"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
